name: Publish OCI Images
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: "Build and publish OCI on GHCR"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Save the date
      id: date
      run: |
        echo date=$(date --rfc-3339=seconds) >> $GITHUB_OUTPUT
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push containers
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: linux/amd64
        tags: |
          ghcr.io/${{ github.repository }}:${{  github.ref_name }}
        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.created=${{ steps.date.outputs.date }}
          org.opencontainers.image.version=${{ steps.date.outputs.tag }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
      